import React from 'react';
import Head from 'next/head';
import Header from 'components/Header';
import Collections from 'components/Collections';

function collectionPage() {
  return (
    <div className={''}>
      <Head>
        <title>NFT Version PaperDoll</title>
        <meta name='description' content='Generated by npx create-web3' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header style={{ padding: '1rem' }}>
        <Header />
      </header>

      <div>
        <Collections />
      </div>
    </div>
  );
}

export default collectionPage;
