import Head from 'next/head';
import Header from 'components/Header';

export default function Home() {
  return (
      <div className={''}>
          <Head>
              <title>NFT Version PaperDoll</title>
              <meta name='description' content='Generated by npx create-web3' />
              <link rel='icon' href='/favicon.ico' />
          </Head>
          <header style={{ padding: '1rem' }}>
              <Header />
          </header>

          <main
              style={{
                  minHeight: '60vh',
                  flex: '1',
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'center',
                  alignItems: 'center',
              }}
          ></main>
      </div>
  );
}
