import Head from 'next/head';
import Header from 'components/Header';
import Minter from 'components/Minter';

export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>NFT Version PaperDoll</title>
        <meta name='description' content='Generated by npx create-web3' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header style={{ padding: '1rem' }}>
        <Header />
      </header>

      <div>
        <Minter />
      </div>
    </div>
  );
}
